#!/bin/bash
python qwen3_tts_clone.py --ref-audio Martin_03.wav --text "Good morning. Today is a calm, bright day, and I’m speaking clearly to capture the natural tone of my voice. Every sentence flows smoothly, with steady pacing and relaxed pronunciation. I’ll vary my rhythm slightly, sometimes slowing down, sometimes speeding up, so the recording sounds realistic and expressive. Numbers like one, two, three, and phrases like twenty-five or ninety-nine help cover different sounds. Names such as Charlie, Houston, and Florida add variety, while simple words like light, shadow, breeze, and water keep everything conversational. I might pause briefly here… then continue speaking in an even, comfortable way. The goal is consistency, clarity, and warmth, as if I’m telling a friendly story to someone nearby. By the end of this passage, my voice should sound natural, balanced, and easy to understand." --instruct "Male, 40 years old, deep gravely, American accent, insecure" -o Martin.wav --device cpu  --no-flash-attn --end-padding 0.5 --samples 5

python qwen3_tts_clone.py --ref-audio Angel_00.wav --text "Good morning. Today is a calm, bright day, and I’m speaking clearly to capture the natural tone of my voice. Every sentence flows smoothly, with steady pacing and relaxed pronunciation. I’ll vary my rhythm slightly, sometimes slowing down, sometimes speeding up, so the recording sounds realistic and expressive. Numbers like one, two, three, and phrases like twenty-five or ninety-nine help cover different sounds. Names such as Charlie, Houston, and Florida add variety, while simple words like light, shadow, breeze, and water keep everything conversational. I might pause briefly here… then continue speaking in an even, comfortable way. The goal is consistency, clarity, and warmth, as if I’m telling a friendly story to someone nearby. By the end of this passage, my voice should sound natural, balanced, and easy to understand." --instruct "Female, 20 years old, American accent, confident untrusting" -o Angel.wav --device cpu  --no-flash-attn --end-padding 0.5 --samples 5

python qwen3_tts_clone.py --ref-audio Thurber_00.wav --text "Good morning. Today is a calm, bright day, and I’m speaking clearly to capture the natural tone of my voice. Every sentence flows smoothly, with steady pacing and relaxed pronunciation. I’ll vary my rhythm slightly, sometimes slowing down, sometimes speeding up, so the recording sounds realistic and expressive. Numbers like one, two, three, and phrases like twenty-five or ninety-nine help cover different sounds. Names such as Charlie, Houston, and Florida add variety, while simple words like light, shadow, breeze, and water keep everything conversational. I might pause briefly here… then continue speaking in an even, comfortable way. The goal is consistency, clarity, and warmth, as if I’m telling a friendly story to someone nearby. By the end of this passage, my voice should sound natural, balanced, and easy to understand." --instruct "Male, 50 years old, British accent, confident, playful" -o Thurber.wav --device cpu  --no-flash-attn --end-padding 0.5 --samples 5

python qwen3_tts_clone.py --ref-audio Bonneville_01.wav --text "Good morning. Today is a calm, bright day, and I’m speaking clearly to capture the natural tone of my voice. Every sentence flows smoothly, with steady pacing and relaxed pronunciation. I’ll vary my rhythm slightly, sometimes slowing down, sometimes speeding up, so the recording sounds realistic and expressive. Numbers like one, two, three, and phrases like twenty-five or ninety-nine help cover different sounds. Names such as Charlie, Houston, and Florida add variety, while simple words like light, shadow, breeze, and water keep everything conversational. I might pause briefly here… then continue speaking in an even, comfortable way. The goal is consistency, clarity, and warmth, as if I’m telling a friendly story to someone nearby. By the end of this passage, my voice should sound natural, balanced, and easy to understand." --instruct "Male, 40 years old, American accent, confident, serious" -o Bonneville.wav --device cpu  --no-flash-attn --end-padding 0.5 --samples 5

python qwen3_tts_clone.py --ref-audio Nanna_00.wav --text "Good morning. Today is a calm, bright day, and I’m speaking clearly to capture the natural tone of my voice. Every sentence flows smoothly, with steady pacing and relaxed pronunciation. I’ll vary my rhythm slightly, sometimes slowing down, sometimes speeding up, so the recording sounds realistic and expressive. Numbers like one, two, three, and phrases like twenty-five or ninety-nine help cover different sounds. Names such as Charlie, Houston, and Florida add variety, while simple words like light, shadow, breeze, and water keep everything conversational. I might pause briefly here… then continue speaking in an even, comfortable way. The goal is consistency, clarity, and warmth, as if I’m telling a friendly story to someone nearby. By the end of this passage, my voice should sound natural, balanced, and easy to understand." --instruct "Female, 60 years old, American accent" -o Nanna.wav --device cpu  --no-flash-attn --end-padding 0.5 --samples 5

python qwen3_tts_clone.py --ref-audio Reggie_00.wav --text "Good morning. Today is a calm, bright day, and I’m speaking clearly to capture the natural tone of my voice. Every sentence flows smoothly, with steady pacing and relaxed pronunciation. I’ll vary my rhythm slightly, sometimes slowing down, sometimes speeding up, so the recording sounds realistic and expressive. Numbers like one, two, three, and phrases like twenty-five or ninety-nine help cover different sounds. Names such as Charlie, Houston, and Florida add variety, while simple words like light, shadow, breeze, and water keep everything conversational. I might pause briefly here… then continue speaking in an even, comfortable way. The goal is consistency, clarity, and warmth, as if I’m telling a friendly story to someone nearby. By the end of this passage, my voice should sound natural, balanced, and easy to understand." --instruct "Male, 40 years old, British accent, confident, formal" -o Reggie.wav --device cpu  --no-flash-attn --end-padding 0.5 --samples 5
